name: ApplicationName
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_modular: any
  flutter_styled_toast: ^2.1.3
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.2
  biometricx: ^0.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets: 
      - assets/


  fonts:
    - family: Secular
      fonts:
        - asset: assets/fonts/SecularOne-Regular.ttf

  uses-material-design: true